services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: builder
    command: sh -c "cd /workspace/apps/backend && air -c .air.toml"
    volumes:
      - ./apps/backend:/workspace/apps/backend
      - ./pkg:/workspace/pkg
      - ./go.work:/workspace/go.work
      - ./go.work.sum:/workspace/go.work.sum
    working_dir: /workspace/apps/backend
    environment:
      - ENV=dev

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      target: builder
    command: sh -c "pnpm install && pnpm dev --host"
    ports:
      - "${HOST_WEB_DEV_PORT:-5173}:5173"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      - WATCH_MODE=true
      - BACKEND_URL=http://backend:8080
      - CI=true
