services:
  backend:
    build:
      target: builder
    command: air -c .air.toml
    volumes:
      - ./apps/backend:/app
    environment:
      - ENV=dev

  web:
    build:
      target: builder
    command: pnpm dev --host
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      - WATCH_MODE=true
